import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRtl: boolean;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: "Huqiqiyy Co-pilot UAE",
    home: "Home",
    findLawyer: "Find a Lawyer",
    myBookings: "My Bookings",
    login: "Login",
    register: "Register",
    logout: "Logout",
    heroTitle: "UAE Law, Explained.",
    heroSubtitle: "Instant, verified legal guidance based on Federal and Local UAE legislation. Navigate your legal journey with confidence.",
    startChat: "Start Legal Consultation",
    howItWorks: "How It Works",
    expertLawyers: "150+ Expert Lawyers",
    verifiedLaws: "Verified UAE Laws",
    instantAdvice: "Instant AI Advice",
    askAssistant: "Technical Legal Copilot",
    typeMessage: "Pose a legal issue, drafting task, or research question...",
    findExpert: "Find Expert",
    needMoreDetail: "Need more detail?",
    formalAssessment: "Formal Assessment",
    consultProfessional: "Consult with a verified professional for binding advice.",
    expertCounsel: "Expert Legal Counsel",
    vettedPros: "Vetted professionals specialized in UAE laws, ready to assist your specific needs.",
    bookConsult: "Book Consultation",
    signInToView: "Sign in to view appointments",
    startListening: "Start listening...",
    stopListening: "Stop listening",
    voiceMode: "Voice Mode",
    enableVoice: "Enable Voice Output",
    uploadPdf: "Upload PDF Document",
    documentAttached: "Document attached",
    removeDocument: "Remove document",
    analyzingDoc: "Analyzing document...",
    uploadImage: "Upload Image",
    takePhoto: "Take Photo",
    imageAttached: "Image attached",
    shareLink: "Share Link",
    copied: "Copied!",
    currency: "AED",
    feePerSession: "Fee per session",
    bookSession: "Book Session",
    specialization: "Specialization",
    maxPrice: "Max Price",
    minRating: "Min Rating",
    anyRating: "Any Rating",
    resetFilters: "Reset Filters",
    noLawyersFound: "No lawyers found",
    adjustFilters: "Try adjusting your filters to find more experts.",
    showingMatches: "Showing",
    lawyerMatches: "lawyers matches",
    analyzingLegislation: "Analyzing Legislation...",
    legalHistory: "Legal History",
    noConversations: "No conversations yet.",
    messagesExchanged: "messages exchanged",
    recordedOn: "Recorded on",
    caseAnalysisReference: "Case Analysis Reference",
    privacySafeguard: "Privacy Safeguard",
    privacyNote: "For your security, original legal documents uploaded during this session were processed strictly in-memory and have been purged from our systems. Only the textual analysis and AI response are retained for your reference.",
    inquiry: "Inquiry",
    systemResponse: "System Response",
    support: "Support",
    admin: "Admin",
    history: "History",
    assistant: "Copilot",
    legislation: "Legislation",
    management: "Management",
    tickets: "Support Tickets",
    resolved: "Resolved",
    active: "Active",
    viewTranscript: "View Transcript",
    noTickets: "No support sessions found.",
    latestMessage: "Latest Message",
    aiSupport: "AI Support",
    aiSupportWelcome: "Hello! I'm your Support Bot. How can I help you today?",
    confirmResolve: "Mark this support session as resolved?",
    lawyer: "Lawyer",
    client: "Client",
    portal: "Portal",
    supportNotice: "Notice: This bot provides technical support only. For legal matters, please schedule a direct consultation with a licensed professional.",
    typeSupportMessage: "Type your support question...",
    adminConsole: "Super Admin Console",
    managementDesc: "Monitor platform activity and manage users.",
    lawyers: "Lawyers",
    newLawyerEmail: "New Lawyer Email",
    authorize: "Authorize",
    addedOn: "Added",
    close: "Close",
    user: "User",
    aiAssistant: "Copilot",
    secureRecords: "Secure Records",
    noHistoryFound: "No history found",
    newInquiry: "New Inquiry",
    caseAnalysisArchive: "Case Analysis Archive",
    intelligenceReport: "Intelligence Report",
    privacyProtocols: "Privacy Protocols",
    selectArchive: "Select an Archive",
    selectArchiveDesc: "Browse your legal history from the sidebar to review past analyses and references.",
    signInGoogle: "Sign in",
    historyDesc: "Access your secure history of legal consultations and AI-driven case analyses.",
    identity: "Identity",
    expertise: "Expertise",
    credentials: "Credentials",
    availability: "Availability",
    received: "Received",
    applicationReceivedDesc: "Thank you for applying to join Huqiqiyy. Our validation team will review your credentials and get back to you via email within 48 hours.",
    returnHome: "Return Home",
    registerAsExpert: "Register as an Expert",
    registerAsExpertDesc: "Expand your legal practice and connect with thousands of clients across the UAE.",
    identityDetails: "Identity Details",
    identityDetailsDesc: "Please provide your official contact information",
    fullLegalName: "Full Legal Name",
    professionalEmail: "Professional Email",
    contactPhone: "Contact Phone",
    legalExpertise: "Legal Expertise",
    legalExpertiseDesc: "Highlight your specialization and experience",
    specializationLabel: "Area(s) of Specialization",
    yearsOfPractice: "Years of Practice",
    professionalBio: "Professional Bio",
    bioPlaceholder: "Brief description of your legal practice and achievements...",
    certification: "Certification",
    certificationDesc: "Proof of license and academic qualifications",
    licenseNumber: "Bar License Number",
    mojPending: "MOJ Verification Pending",
    highestEducation: "Highest Education",
    consultationFee: "Consultation Fee (AED)",
    feeNote: "Must be a multiple of 50 AED",
    uploadLicense: "Upload Digital License",
    pdfMax10: "PDF or High-quality Image (Max 10MB)",
    availabilityDesc: "Configure your working hours and session preferences",
    workingHoursWeekday: "Standard Working Hours (Mon-Thu)",
    start: "Start",
    end: "End",
    fridayHours: "Friday Special Hours",
    fridayOffDayNote: "Friday is an Off Day",
    offDays: "Off Days",
    availabilitySetting: "Availability Setting",
    availabilitySettingDesc: "You can manage your Out of Office status in your profile settings after registration.",
    back: "Back",
    submitApplication: "Submit Application",
    continue: "Continue",
    providerTermsNote: "By submitting, you agree to our Provider Terms and represent all data as truthful.",
    step: "Step",
    limit2Digits: "Limit: 2 Digits",
    wordCount: "Words",
    managementPortal: "Management Portal",
    availabilitySettings: "Availability Settings",
    availabilitySettingsDesc: "Manage your calendar, working hours, and visibility.",
    saveChanges: "Save Changes",
    savedSuccessfully: "Saved Successfully",
    visibilityStatus: "Visibility Status",
    oooToggle: "Out of Office (OOO) Toggle",
    currentlyUnavailable: "Currently Unavailable",
    currentlyAvailable: "Currently Available",
    oooHidden: "Your profile is hidden from clients. You won't receive new consultation requests.",
    oooVisible: "Your profile is visible in the directory and clients can book consultations.",
    scheduledDaysOff: "Scheduled Days Off",
    selectHolidays: "Select your weekly holidays",
    standardWorkingHours: "Standard Hours",
    sessionTimingDesc: "Session timing configuration",
    weekdayHoursLabel: "Weekday Hours (Mon - Thu)",
    offDay: "Off Day",
    smartSlotGeneration: "Smart Slot Generation",
    slotGenerationDesc: "\"Personal visits\" are automatically generated as 1-hour slots. \"Video consultations\" are generated as 30-minute slots.",
    noProfileFound: "No Lawyer Profile Found",
    noProfileFoundDesc: "You need to complete your lawyer registration first.",
    registerAsLawyer: "Register as Lawyer",
    joinNetwork: "Join the Network",
    application: "Application",
    emiratesIdPlaceholder: "As per Emirates ID",
    uaeNumbersOnly: "UAE Numbers Only",
    scheduling: "Scheduling",
    legislationDirectory: "UAE Legislation Directory",
    legislationDirectoryDesc: "Explore the library of UAE laws with AI-guided search.",
    exploreLaws: "Explore Laws",
    laborLaw: "Labor Law",
    laborLawDesc: "Private sector employment relations, contracts, and gratuity.",
    commercialLaw: "Commercial Law",
    commercialLawDesc: "Business regulations, companies, and commercial agency laws.",
    propertyLaw: "Property & Real Estate",
    propertyLawDesc: "Laws governing ownership, tenancy, and real estate development.",
    civilLaw: "Civil Transactions",
    civilLawDesc: "General civil rights, obligations, and contract laws.",
    criminalLaw: "Criminal Law",
    criminalLawDesc: "UAE penal code, crimes, and legal procedures.",
    personalStatusLaw: "Personal Status",
    personalStatusLawDesc: "Marriage, divorce, inheritance, and child custody.",
    loadingProfile: "Loading Profile...",
    expertNotFound: "Expert Not Found",
    returnToDirectory: "Return to Directory",
    chooseDate: "Choose Date",
    chooseTime: "Choose Time",
    consultationType: "Consultation Type",
    videoCall: "Video Call",
    inPerson: "In-Person",
    meetLinkNote: "A secure Google Meet link will be generated for this session.",
    finalTotal: "Final Total",
    bookNow: "Book Now",
    education: "Education",
    languages: "Languages",
    biography: "Biography",
    professional: "Professional",
    reviewCount: "Reviews",
    experienceLabel: "Experience",
    clientFeedback: "Client Feedback",
    loadMoreReviews: "Load More Reviews",
    confirmBooking: "Confirm Booking",
    bookConsultationWith: "Book a consultation with",
    meetLinkSharedNote: "Your booking request will be shared with the expert for final confirmation.",
    schedule: "Schedule",
    type: "Type",
    aiStrategicAssociate: "AI Strategic Associate",
    privacy: "Privacy",
    terms: "Terms",
    joinAsLawyer: "Join as Lawyer",
    referral: "Referral",
    becomeClient: "Become Client",
    becomeLawyer: "Become Lawyer",
    referralCopied: "Referral link copied to clipboard!",
    professionalEnvironment: "Professional Environment",
    aiCoPilot: "Huqiqiyy Co-pilot",
    aiCoPilotDesc: "Your technical research copilot for case law, regulations, and procedural nuances in the UAE.",
    launchAIStrategicAssociate: "Launch AI Strategic Associate",
    upcomingAppointment: "Upcoming Appointment",
    confirmed: "CONFIRMED",
    commercialLeaseReview: "Commercial Lease Review",
    regulatoryIntelligence: "Regulatory Intelligence",
    regulatoryIntelligenceDesc: "Direct access to UAE Federal & Local decrees with semantic search.",
    technicalDrafting: "Technical Drafting",
    technicalDraftingDesc: "AI-assisted outlines for memorandums, notices, and legal briefs.",
    proceduralClarity: "Procedural Clarity",
    proceduralClarityDesc: "Step-by-step litigation timelines and jurisdictional guidance.",
    globalLegalSync: "Global Legal Sync",
    system: "System",
    analytics: "Analytics",
    usageOverview: "Usage Overview",
    apiRequests: "API Requests",
    noUsageData: "No usage data found for the selected period.",
    totalRequests: "Total Requests",
    successRate: "Success Rate",
    last7Days: "Last 7 Days",
  },
  ar: {
    appName: "هويقيقي كودبايلوت الإمارات",
    home: "الرئيسية",
    findLawyer: "ابحث عن محامٍ",
    myBookings: "حجوزاتي",
    login: "تسجيل الدخول",
    register: "التسجيل",
    logout: "تسجيل الخروج",
    heroTitle: "قوانين الإمارات، مبسطة.",
    heroSubtitle: "إرشادات قانونية فورية وموثقة بناءً على التشريعات الاتحادية والمحلية لدولة الإمارات. ابدأ رحلتك القانونية بثقة.",
    startChat: "ابدأ الاستشارة القانونية",
    howItWorks: "كيف يعمل النظام",
    expertLawyers: "أكثر من 150 محامٍ خبير",
    verifiedLaws: "قوانين إماراتية موثقة",
    instantAdvice: "نصيحة فورية بالذكاء الاصطناعي",
    askAssistant: "المساعد القانوني التقني",
    typeMessage: "اطرح مسألة قانونية أو مهمة صياغة أو سؤال بحثي...",
    findExpert: "ابحث عن خبير",
    needMoreDetail: "هل تحتاج إلى مزيد من التفاصيل؟",
    formalAssessment: "تقييم رسمي",
    consultProfessional: "استشر متخصصاً معتمداً للحصول على نصيحة ملزمة.",
    expertCounsel: "استشارات قانونية من خبراء",
    vettedPros: "متخصصون معتمدون في قوانين الإمارات، جاهزون لمساعدتك.",
    bookConsult: "حجز استشارة",
    signInToView: "سجل الدخول لعرض المواعيد",
    startListening: "بدء الاستماع...",
    stopListening: "إيقاف الاستماع",
    voiceMode: "الوضع الصوتي",
    enableVoice: "تفعيل الإخراج الصوتي",
    uploadPdf: "تحميل مستند PDF",
    documentAttached: "المستند مرفق",
    removeDocument: "إزالة المستند",
    analyzingDoc: "جاري تحليل المستند...",
    uploadImage: "تحميل صورة",
    takePhoto: "التقاط صورة",
    imageAttached: "الصورة مرفقة",
    shareLink: "مشاركة الرابط",
    copied: "تم النسخ!",
    currency: "درهم",
    feePerSession: "رسوم الجلسة",
    bookSession: "حجز جلسة",
    specialization: "التخصص",
    maxPrice: "السعر الأقصى",
    minRating: "التقييم الأدنى",
    anyRating: "أي تقييم",
    resetFilters: "إعادة ضبط الفلاتر",
    noLawyersFound: "لم يتم العثور على محامين",
    adjustFilters: "حاول تعديل الفلاتر للعثور على المزيد من الخبراء.",
    showingMatches: "عرض",
    lawyerMatches: "محامين مطابقين",
    analyzingLegislation: "جاري تحليل التشريعات...",
    legalHistory: "السجل القانوني",
    noConversations: "لا توجد محادثات بعد.",
    messagesExchanged: "رسائل متبادلة",
    recordedOn: "سجل في",
    caseAnalysisReference: "مرجع تحليل الحالة",
    privacySafeguard: "ضمان الخصوصية",
    privacyNote: "لأمانك، تم التعامل مع المستندات القانونية الأصلية المحملة خلال هذه الجلسة في الذاكرة فقط وتم مسحها من أنظمتنا. يتم الاحتفاظ فقط بالتحليل النصي واستجابة الذكاء الاصطناعي للرجوع إليها.",
    inquiry: "استفسار",
    systemResponse: "استجابة النظام",
    support: "الدعم",
    admin: "لوحة التحكم",
    history: "السجل",
    assistant: "كودبايلوت",
    legislation: "التشريعات",
    management: "الإدارة",
    tickets: "تذاكر الدعم",
    resolved: "تم الحل",
    active: "نشط",
    viewTranscript: "عرض السجل",
    noTickets: "لم يتم العثور على جلسات دعم.",
    latestMessage: "آخر رسالة",
    aiSupport: "الدعم بالذكاء الاصطناعي",
    aiSupportWelcome: "مرحباً! أنا بوت الدعم الخاص بك. كيف يمكنني مساعدتك اليوم؟",
    confirmResolve: "هل تريد وضع علامة 'محلولة' على هذه الجلسة؟",
    lawyer: "محامٍ",
    client: "عميل",
    portal: "بوابة",
    supportNotice: "تنبيه: هذا المساعد يقدم دعماً فنياً فقط. للمسائل القانونية، يرجى حجز استشارة مباشرة مع محامٍ معتمد.",
    typeSupportMessage: "اكتب سؤال الدعم هنا...",
    adminConsole: "لوحة تحكم المسؤول الخارق",
    managementDesc: "مراقبة نشاط المنصة وإدارة المستخدمين.",
    lawyers: "المحامون",
    newLawyerEmail: "بريد المحامي الجديد",
    authorize: "اعتماد",
    addedOn: "تمت الإضافة",
    close: "إغلاق",
    user: "المستخدم",
    aiAssistant: "كودبايلوت",
    secureRecords: "سجلات آمنة",
    noHistoryFound: "لم يتم العثور على سجل",
    newInquiry: "استفسار جديد",
    caseAnalysisArchive: "أرشيف تحليل الحالات",
    intelligenceReport: "تقرير الذكاء الاصطناعي",
    privacyProtocols: "بروتوكولات الخصوصية",
    selectArchive: "اختر أرشيفاً",
    selectArchiveDesc: "تصفح سجلك القانوني من الشريط الجانبي لمراجعة التحليلات والمراجع السابقة.",
    signInGoogle: "تسجيل الدخول",
    historyDesc: "الوصول إلى سجلك الآمن من الاستشارات القانونية وتحليلات الحالات المدعومة بالذكاء الاصطناعي.",
    identity: "الهوية",
    expertise: "الخبرة",
    credentials: "الاعتمادات",
    availability: "التوفر",
    received: "تم الاستلام",
    applicationReceivedDesc: "شكراً لتقديم طلب الانضمام إلى هويقيقي. سيقوم فريق التحقق لدينا بمراجعة اعتماداتك والرد عليك عبر البريد الإلكتروني خلال 48 ساعة.",
    returnHome: "العودة للرئيسية",
    registerAsExpert: "سجل كخبير",
    registerAsExpertDesc: "وسع ممارستك القانونية وتواصل مع آلاف العملاء في جميع أنحاء الإمارات.",
    identityDetails: "تفاصيل الهوية",
    identityDetailsDesc: "يرجى تقديم معلومات الاتصال الرسمية الخاصة بك",
    fullLegalName: "الاسم القانوني الكامل",
    professionalEmail: "البريد الإلكتروني المهني",
    contactPhone: "هاتف الاتصال",
    legalExpertise: "الخبرة القانونية",
    legalExpertiseDesc: "سلط الضوء على تخصصك وخبرتك",
    specializationLabel: "مجالات التخصص",
    yearsOfPractice: "سنوات الممارسة",
    professionalBio: "السيرة الذاتية المهنية",
    bioPlaceholder: "وصف موجز لممارستك القانونية وإنجازاتك...",
    certification: "الشهادات",
    certificationDesc: "إثبات الترخيص والمؤهلات الأكاديمية",
    licenseNumber: "رقم رخصة المحاماة",
    mojPending: "في انتظار التحقق من وزارة العدل",
    highestEducation: "أعلى مؤهل تعليمي",
    consultationFee: "رسوم الاستشارة (درهم)",
    feeNote: "يجب أن يكون مضاعفاً لـ 50 درهماً",
    uploadLicense: "تحميل الرخصة الرقمية",
    pdfMax10: "PDF أو صورة عالية الجودة (بحد أقصى 10 ميجابايت)",
    availabilityDesc: "تكوين ساعات العمل وتفضيلات الجلسات",
    workingHoursWeekday: "ساعات العمل القياسية (الإثنين - الخميس)",
    start: "البداية",
    end: "النهاية",
    fridayHours: "ساعات الجمعة الخاصة",
    fridayOffDayNote: "الجمعة يوم عطلة",
    offDays: "أيام العطلة",
    availabilitySetting: "إعدادات التوفر",
    availabilitySettingDesc: "يمكنك إدارة حالة 'خارج المكتب' في إعدادات ملفك الشخصي بعد التسجيل.",
    back: "رجوع",
    submitApplication: "إرسال الطلب",
    continue: "استمرار",
    providerTermsNote: "بتقديمك الطلب، فأنت توافق على شروط المزود الخاصة بنا وتقر بأن جميع البيانات صحيحة.",
    step: "الخطوة",
    limit2Digits: "الحد الأقصى: رقمان",
    wordCount: "كلمة",
    managementPortal: "بوابة الإدارة",
    availabilitySettings: "إعدادات التوفر",
    availabilitySettingsDesc: "إدارة التقويم وساعات العمل والظهور.",
    saveChanges: "حفظ التغييرات",
    savedSuccessfully: "تم الحفظ بنجاح",
    visibilityStatus: "حالة الظهور",
    oooToggle: "تبديل وضع خارج المكتب (OOO)",
    currentlyUnavailable: "غير متاح حالياً",
    currentlyAvailable: "متاح حالياً",
    oooHidden: "ملفك الشخصي مخفي عن العملاء. لن تتلقى طلبات استشارة جديدة.",
    oooVisible: "ملفك الشخصي مرئي في الدليل ويمكن للعملاء حجز استشارات.",
    scheduledDaysOff: "أيام العطلة المجدولة",
    selectHolidays: "اختر عطلاتك الأسبوعية",
    standardWorkingHours: "ساعات العمل القياسية",
    sessionTimingDesc: "تكوين توقيت الجلسات",
    weekdayHoursLabel: "ساعات أيام الأسبوع (الإثنين - الخميس)",
    offDay: "يوم عطلة",
    smartSlotGeneration: "توليد الفترات الذكي",
    slotGenerationDesc: "يتم توليد 'الزيارات الشخصية' تلقائياً كفترات مدتها ساعة واحدة. يتم توليد 'الاستشارات المرئية' كفترات مدتها 30 دقيقة.",
    noProfileFound: "لم يتم العثور على ملف محامٍ",
    noProfileFoundDesc: "يجب عليك إكمال تسجيل المحامي أولاً.",
    registerAsLawyer: "سجل كمحامٍ",
    joinNetwork: "انضم إلى الشبكة",
    application: "طلب",
    emiratesIdPlaceholder: "كما في الهوية الإماراتية",
    uaeNumbersOnly: "الأرقام الإماراتية فقط",
    scheduling: "الجدولة",
    legislationDirectory: "دليل التشريعات الإماراتية",
    legislationDirectoryDesc: "استكشف مكتبة القوانين الإماراتية من خلال البحث الموجه بالذكاء الاصطناعي.",
    exploreLaws: "استكشاف القوانين",
    laborLaw: "قانون العمل",
    laborLawDesc: "علاقات العمل في القطاع الخاص، العقود، ومكافآت نهاية الخدمة.",
    commercialLaw: "القانون التجاري",
    commercialLawDesc: "لوائح الأعمال، الشركات، وقوانين الوكالات التجارية.",
    propertyLaw: "قانون الملكية والعقارات",
    propertyLawDesc: "القوانين المنظمة للملكية، الإيجار، والتطوير العقاري.",
    civilLaw: "المعاملات المدنية",
    civilLawDesc: "الحقوق المدنية العامة، الالتزامات، وقوانين العقود.",
    criminalLaw: "القانون الجنائي",
    criminalLawDesc: "قانون العقوبات الإماراتي، الجرائم، والإجراءات القانونية.",
    personalStatusLaw: "الأحوال الشخصية",
    personalStatusLawDesc: "الزواج، الطلاق، الميراث، وحضانة الأطفال.",
    loadingProfile: "جاري تحميل الملف الشخصي...",
    expertNotFound: "الخبير غير موجود",
    returnToDirectory: "العودة إلى الدليل",
    chooseDate: "اختر التاريخ",
    chooseTime: "اختر الوقت",
    consultationType: "نوع الاستشارة",
    videoCall: "مكالمة فيديو",
    inPerson: "وجهاً لوجه",
    meetLinkNote: "سيتم إنشاء رابط Google Meet آمن لهذه الجلسة.",
    finalTotal: "الإجمالي النهائي",
    bookNow: "احجز الآن",
    education: "التعليم",
    languages: "اللغات",
    biography: "السيرة الذاتية",
    professional: "مهني",
    reviewCount: "تقييمات",
    experienceLabel: "الخبرة",
    clientFeedback: "آراء العملاء",
    loadMoreReviews: "تحميل المزيد من التقييمات",
    confirmBooking: "تأكيد الحجز",
    bookConsultationWith: "حجز استشارة مع",
    meetLinkSharedNote: "سيتم مشاركة طلب الحجز الخاص بك مع الخبير للتأكيد النهائي.",
    schedule: "الجدول الزمني",
    type: "النوع",
    aiStrategicAssociate: "مساعد الذكاء الاصطناعي الاستراتيجي",
    privacy: "الخصوصية",
    terms: "الشروط",
    joinAsLawyer: "انضم كمحامٍ",
    referral: "الإحالة",
    becomeClient: "تحول إلى عميل",
    becomeLawyer: "تحول إلى محامٍ",
    referralCopied: "تم نسخ رابط الإحالة إلى الحافظة!",
    professionalEnvironment: "بيئة مهنية",
    aiCoPilot: "مساعد هويقيقي",
    aiCoPilotDesc: "مساعد البحث الفني الخاص بك للاجتهادات القضائية واللوائح والتفاصيل الإجرائية في الإمارات.",
    launchAIStrategicAssociate: "إطلاق المساعد الاستراتيجي الذكي",
    upcomingAppointment: "الموعد القادم",
    confirmed: "مؤكد",
    commercialLeaseReview: "مراجعة عقد إيجار تجاري",
    regulatoryIntelligence: "الذكاء التنظيمي",
    regulatoryIntelligenceDesc: "وصول مباشر للمراسيم الاتحادية والمحلية مع بحث دلالي.",
    technicalDrafting: "الصياغة الفنية",
    technicalDraftingDesc: "مخططات مدعومة بالذكاء الاصطناعي للمذكرات والإخطارات والموجزات القانونية.",
    proceduralClarity: "الوضوح الإجرائي",
    proceduralClarityDesc: "جداول زمنية للتقاضي خطوة بخطوة وإرشادات حول الاختصاص القضائي.",
    globalLegalSync: "المزامنة القانونية العالمية",
    system: "النظام",
    analytics: "التحليلات",
    usageOverview: "نظرة عامة على الاستخدام",
    apiRequests: "طلبات واجهة البرمجيات",
    noUsageData: "لا توجد بيانات استخدام للفترة المحددة.",
    totalRequests: "إجمالي الطلبات",
    successRate: "نسبة النجاح",
    last7Days: "آخر 7 أيام",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_lang');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_lang', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => translations[language][key] || key;
  const isRtl = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRtl, t }}>
      <div className={isRtl ? 'font-arabic' : 'font-sans'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
